# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GuideBot' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GuideBot
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  target 'GuideBotUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
